name: "upload"

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: upload-workflow
  cancel-in-progress: true

jobs:
  upload-files:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: Clone local repository
        uses: actions/checkout@v2
      - name: Get version
        run: |
          ver=$(cat addon.xml | grep script.lyricsfontsize | grep -o "[0-9]\.[\.0-9]*")
          echo "VERSION=$ver" >> $GITHUB_ENV
      - name: Move files
        run: |
          mkdir script.lyricsfontsize
          rm -rf .github .git .gitignore public
          shopt -s extglob
          mv !(script.lyricsfontsize) script.lyricsfontsize
      - name: Upload addon
        uses: actions/upload-artifact@v2
        with:
          name: script.lyricsfontsize-${{ env.VERSION }}-python3
          path: ./
